version: '3.7'

services:
  kitties-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    environment:
      - BASE_URL=http://ec2-35-172-119-67.compute-1.amazonaws.com
      - DATABASE_URL=mongodb://mongo
    env_file:
      - .env
  mongo:
    image: mongo
    restart: always
